#!/bin/sh
# Validate the submitted commit message
MSG="$1"

# regex and message for version validation in commit message
version_regex='(version: [0-9]+\.[0-9]+\.[0-9]+[.]*)'
version_error_msg="Aborting commit. Your commit message is missing a version in the format 'version: 1.0.0'"

# regex and message for tag validation in commit message
tag_regex="(tag: (Added|Removed|Changed|Fixed|Deprecated|Maintenance)$)"
tag_error_msg="Aborting commit. Your commit message is missing a tag in the format 'tag: <accepted-tag>' Currently accepted tags are Added, Removed, Changed, Fixed, Deprecated, Maintenance"

if ! grep -iqE "$reference_regex" "$MSG"; then
    echo "$reference_error_msg" >&2
    exit 1
fi
if ! grep -iqE "$version_regex" "$MSG"; then
    echo "$version_error_msg" >&2
    exit 1
fi

if ! grep -iqE "$tag_regex" "$MSG"; then
    echo "$tag_error_msg" >&2
    exit 1
fi